# -*- coding: utf-8 -*-
"""Answer 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FyAJa5P2FOpja-xhxx_ARW83U4CFNIyn
"""

#Ans: 2

i=0
n = int(input("Number of element:"))
list_one=[]
list_two=[]
print("Enter List Element :5")
while i < n:
  list_one.append(int(input()))
  i=i+1
for i in list_one:
  if i not in list_two:
    list_two.append(i)

print("Input List",list_one)