# -*- coding: utf-8 -*-
"""Answer 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ufKMfHFFv_Z-pbV_8vGPFpXan2LqLHT_
"""

#Question 5

def prime(x):
  
   if x > 1 :
        for i in range(2,x+1):
            if x%i==0:
                break

        if x==i:
          print(x)
         

     



x=int(input("Enter lower limit "))
y=int(input("Enter upper limit: "))

for i in range (x,y):
  x=x+1
 
  prime(x)