# -*- coding: utf-8 -*-
"""Answer 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0QeDdP4hjqNiNLpPrWMfHXGXGetmA34
"""

string = (input ("Enter String :")) 
a=string[0]


temp_list = list(string)

for i in range (1,len(temp_list)):
  if temp_list[i]==a:
          temp_list[i] = "$"
          
#converting list back to string
string = ''.join(temp_list)
print(string)