# -*- coding: utf-8 -*-
"""Answer 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g8AEcOrtGkMVwUwOEewRLwxdlbZ2x1tC
"""

#Ans:3


count=0
i=0
n = int(input("Number of element:"))
list_one=[]
list_two=[]
list_three=[]
print("Enter List Element :5")
while i < n:
  list_one.append(int(input()))
  i=i+1
for i in list_one:
  if i % 2 == 0 not in list_two:
    list_two.append(i)
    count=count+1

for i in list_one:
  if i not in list_two:
    list_three.append(i)
    


print("Input List",list_one)
print("EvenCount",count)
updated_list=[]
updated_list=list_three
print("Updated list",updated_list)