# -*- coding: utf-8 -*-
"""Answer 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iorI2o7Qm1TT_bCQ_Wyw7GClOHmOhmjG
"""

#Ans:4

a=4
i=0

for i in range(a):
  for j in range(i):
    print("*",end="")
  print("\r")

for i in range(a,0,-1):
  for j in range(i):
    print("*",end="")  #end for remove new line after the *
  print("\r")